let name = "Susheel Kuamr";
let school="Masai School";
let section="A2";
let grade="A";
let rollno=240564;
let English, Math, Science;
English=88;
Math=89;
Science=86;
console.log("Name :" ,name);
console.log("School :" ,school);
console.log("Grade :" ,grade);
console.log("Section :" ,section);
console.log("Roll no :" ,rollno);
console.log("Scored marks in 3 Subjects :" ,English+Math+Science);